### ISSUE TITLE
Show Fatal Error When Call API

### ISSUE THREAD

**Issue by hareshpatel1990** [patarkf/cakephp3restapi#1]
Hi Patrick,
This is nice to see that there is a way to making RESTFUL API in cakephp, this repository is useful for me if it works, I am getting error when try to call an API 

**Request Call**

```
http://localhost:90/restful/api/users/register
```

**I am getting following error in postman**

```
Fatal error: Call to a member function set() on a non-object in C:\wamp\www\restful\vendor\friendsofcake\crud\src\Action\BaseAction.php on line 193
```

**Comment by patarkf** [comment]
Hey,

I'm sorry for my late response, I was a little inactive from Github and actually I didn't see this issue, but I'll try to be more active now. :) Did you get a solution for this problem? Let me know and we can find a solution for it.

Thanks.

**Comment by TakesTheBiscuit** [comment]
Hello.

I had to add
use Firebase\JWT\JWT;
to Controllers/api/UsersController.php

I then had to edit the same file inside the add() function where the token is generated to read:
\Firebase\JWT\JWT::encode(
_instead_ of \JWT::encode(

Now generates tokens nicely which helps!!

**Comment by TakesTheBiscuit** [comment]
Further to the above.
Controller/Api/AppController.php
Add to the $components array:
'Flash'
This solves all issues :-) :8ball:
